### ISSUE TITLE
"generate text" in README

### ISSUE THREAD

**Issue by aparatext** [Haste171/gptzero#1]
> This is a Python wrapper for the GPTZero API, which allows you to **generate natural language text using GPT technology**. This wrapper provides a simple way to interact with the GPTZero API using Python.

I'd say the first lines of README should be rewritten, since they were likely hallucinated by GPT-3. This ambiguity may make the project less discoverable or possibly confuse the users.

**Comment by Haste171** [comment]
Indeed
